text_type_text: str = "text"
text_type_bold: str = "bold"
text_type_italic: str = "italic"
text_type_code: str = "code"
text_type_link: str = "link"
text_type_image: str = "image"

block_type_paragraph: str = "paragraph"
block_type_heading: str = "heading"
block_type_code: str = "code"
block_type_quote: str = "quote"
block_type_unordered_list: str = "unordered_list"
block_type_ordered_list: str = "ordered_list"
block_type_newline: str = "newline"
